export const INDICATOR_DATA = {
  'Yield Curve (2Y–10Y)': {
    tier: 1, weight: '14%',
    what: 'The spread between 2-year and 10-year US Treasury yields. When negative (inverted), short-term rates exceed long-term rates — the market\'s signal that it expects economic slowdown ahead.',
    why: 'Has preceded every US recession in the last 50 years. When the curve inverts, the duration of inversion tends to matter more than its depth, and the Fed typically begins cutting rates 6–18 months after an inversion begins.',
    thresholds: [
      ['> +0.5%','OK','Normal expansionary slope'],
      ['0 to +0.5%','CAUTION','Flattening — watch trend'],
      ['0 to −0.5%','WARNING','Inverted — elevated recession risk'],
      ['< −0.5%','ALERT','Deep inversion — high recession probability'],
    ],
    source: 'FRED', fredId: 'T10Y2Y',
    fredUrl: 'https://fred.stlouisfed.org/series/T10Y2Y',
  },
  'ISM Manufacturing PMI': {
    tier: 1, weight: '12%',
    what: 'Monthly survey of US manufacturing purchasing managers. Readings above 50 signal expansion; below 50 signal contraction.',
    why: 'Manufacturing is a reliable leading indicator of broader economic health. Sustained readings below 47 — typically three consecutive months — signal contraction spreading into the wider economy.',
    thresholds: [
      ['> 55','OK','Strong expansion'],
      ['50–55','CAUTION','Slowing growth'],
      ['46–50','WARNING','Contraction territory'],
      ['< 46','ALERT','Deep contraction'],
    ],
    source: 'Institute for Supply Management',
    fredUrl: 'https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/',
  },
  'Unemployment Claims': {
    tier: 1, weight: '11%',
    what: 'Weekly initial jobless claims (4-week moving average). Measures new unemployment insurance filings across the US.',
    why: 'Rising claims lead broader unemployment by 2–4 months. A confirmed upward trend crossing roughly 245k is a reliable late-cycle signal. As a coincident labor read, it acts as the model\'s confirmation gate before the deeper contraction and crisis phases.',
    thresholds: [
      ['< 220k','OK','Tight labor market'],
      ['220–240k','CAUTION','Normal range — watch trend'],
      ['240–260k','WARNING','Rising trend — elevated risk'],
      ['> 260k','ALERT','Labor market softening'],
    ],
    source: 'FRED', fredId: 'ICSA',
    fredUrl: 'https://fred.stlouisfed.org/series/ICSA',
  },
  'CPI Year-over-Year': {
    tier: 1, weight: '9%',
    what: 'Consumer Price Index, year-over-year change. Measures the rate of change in consumer prices across a broad basket of goods and services.',
    why: 'Above-target inflation constrains Fed easing and keeps real rates elevated. Inflation + slowing growth = stagflation — the most challenging macro environment for traditional portfolios.',
    thresholds: [
      ['< 2%','OK','At or below Fed target'],
      ['2–3%','CAUTION','Above target — watch trend'],
      ['3–5%','WARNING','Materially above target'],
      ['> 5%','ALERT','High inflation — policy constrained'],
    ],
    source: 'FRED', fredId: 'CPIAUCSL',
    fredUrl: 'https://fred.stlouisfed.org/series/CPIAUCSL',
  },
  'Leading Indicator Index': {
    tier: 2, weight: '6%',
    what: 'Conference Board US Leading Economic Index — a composite of 10 forward-looking sub-components spanning financial markets, labor, and manufacturing.',
    why: 'Designed to turn before the broader economy. A sustained decline — on the order of four of the last five months — signals deteriorating forward momentum.',
    composite: 'A forward-looking composite input to the regime model. Persistent decline shifts classification pressure toward Contraction.',
    thresholds: [['Rising','OK','Expansion signal'],['Flat','CAUTION','Momentum stalling'],['Declining 1–3 months','WARNING','Slowdown building'],['Declining 4+ months','ALERT','Contraction probable']],
    source: 'FRED', fredId: 'USSLIND',
    fredUrl: 'https://fred.stlouisfed.org/series/USSLIND',
  },
  'Conf. Board LEI YoY': {
    tier: 2, weight: '7%',
    what: 'Year-over-year change in the Conference Board Leading Economic Index. Smooths base effects better than month-over-month.',
    why: 'Six consecutive negative YoY readings have historically coincided with recession onset within 3–6 months.',
    composite: 'Confirms the raw LEI direction. Two negative LEI inputs together create strong Contraction signal pressure in the composite.',
    thresholds: [['> +2%','OK','Strong forward momentum'],['0 to +2%','CAUTION','Slowing momentum'],['0 to −3%','WARNING','Contraction signal'],['< −3%','ALERT','Recession-level reading']],
    source: 'Conference Board',
    fredUrl: 'https://www.conference-board.org/topics/us-leading-indicators',
  },
  'S&P 500 vs 200 DMA': {
    tier: 2, weight: '5%',
    what: 'S&P 500 index price relative to its 200-day moving average. A widely used technical trend indicator.',
    why: 'Sustained trading below the 200 DMA signals deteriorating equity market internals and confirms fundamental regime readings.',
    composite: 'Market signal input. Weighted lower than fundamental indicators but confirms trend direction in the composite model.',
    thresholds: [['> +5%','OK','Strong uptrend'],['0 to +5%','CAUTION','Near trend line'],['0 to −5%','WARNING','Below 200 DMA'],['< −5%','ALERT','Sustained downtrend']],
    source: 'Alpha Vantage / Yahoo Finance',
    fredUrl: 'https://finance.yahoo.com/quote/%5EGSPC/',
  },
  'High Yield Spreads': {
    tier: 2, weight: '10%',
    what: 'ICE BofA US High Yield Index Option-Adjusted Spread. Measures the yield premium of sub-investment grade bonds over equivalent Treasuries.',
    why: 'Widening spreads signal deteriorating credit conditions and rising default expectations. The highest-weighted credit indicator in the model.',
    composite: 'Credit model anchor. Spread widening above 5% has historically coincided with Late Cycle → Contraction transition.',
    thresholds: [['< 3%','OK','Tight credit conditions'],['3–4.5%','CAUTION','Elevated but stable'],['4.5–6%','WARNING','Widening — stress building'],['> 6%','ALERT','Credit market stress']],
    source: 'FRED', fredId: 'BAMLH0A0HYM2',
    fredUrl: 'https://fred.stlouisfed.org/series/BAMLH0A0HYM2',
  },
  'Fed Funds Rate': {
    tier: 2, weight: '5%',
    what: 'Federal Reserve target rate for overnight interbank lending. The primary monetary policy instrument.',
    why: 'Rate relative to neutral (r*) matters more than the absolute level. Policy near the estimated neutral rate is neither stimulative nor restrictive; the further above neutral the rate sits, the more restrictive the stance.',
    composite: 'Policy stance input. The model uses the spread between the current rate and the estimated neutral rate.',
    thresholds: [['Below neutral','OK','Accommodative policy'],['Near neutral','CAUTION','Balanced'],['Above neutral','WARNING','Restrictive'],['Materially above neutral','ALERT','Tight conditions']],
    source: 'FRED', fredId: 'FEDFUNDS',
    fredUrl: 'https://fred.stlouisfed.org/series/FEDFUNDS',
  },
  '10yr TIPS Real Yield': {
    tier: 2, weight: '8%',
    what: '10-year Treasury Inflation-Protected Securities yield. Measures the real (inflation-adjusted) return on long-term US government debt.',
    why: 'Positive real yields raise the cost of capital economy-wide. The higher real rates climb, the greater the structural headwind to growth and asset prices.',
    composite: 'Real rate input. Readings above 1.5% are historically associated with Late Cycle → Contraction pressure in the composite model.',
    thresholds: [['< 0%','OK','Negative real rates — stimulative'],['0–1%','CAUTION','Near neutral'],['1–2.5%','WARNING','Restrictive real rates'],['> 2.5%','ALERT','Highly restrictive']],
    source: 'FRED', fredId: 'DFII10',
    fredUrl: 'https://fred.stlouisfed.org/series/DFII10',
  },
  'Copper / Gold Ratio': {
    tier: 2, weight: '9%',
    what: 'Ratio of copper to gold price. Copper reflects industrial demand; gold reflects safe-haven demand. Together they measure global risk appetite.',
    why: 'A falling ratio means gold is outperforming copper — declining global growth expectations and rising risk aversion. Below 0.20 has preceded Late Cycle → Contraction transitions.',
    composite: 'Risk appetite input. Falling ratio confirms the fundamental regime signal from yield curve and credit indicators.',
    thresholds: [['> 0.25','OK','Risk-on, growth expected'],['0.20–0.25','CAUTION','Declining risk appetite'],['0.15–0.20','WARNING','Risk-off signal'],['< 0.15','ALERT','Strong risk-off']],
    source: 'Alpha Vantage / Quandl',
    fredUrl: 'https://www.macrotrends.net/1441/copper-gold-ratio',
  },
  'USD DXY': {
    tier: 2, weight: '4%',
    what: 'US Dollar Index — measures the dollar against a trade-weighted basket of major currencies (EUR, JPY, GBP, CAD, SEK, CHF).',
    why: 'Dollar strength at multi-year extremes creates global financial tightening. Readings in the 100–107 band have historically preceded multi-year reversals.',
    composite: 'Currency model input. Extreme readings feed both the regime model and the currency strategy trigger criteria.',
    thresholds: [['< 95','OK','Dollar weakness — loose global liquidity'],['95–102','CAUTION','Normal range'],['102–108','WARNING','Elevated — approaching extreme'],['> 108','ALERT','Multi-year extreme']],
    source: 'FRED', fredId: 'DTWEXBGS',
    fredUrl: 'https://fred.stlouisfed.org/series/DTWEXBGS',
  },
};

export const ARTICLE_MAP = {
  'annual-letter-2025':             '/articles/annual-letter-2025-draft.html',
  'regime-briefing-may-2026':       '/articles/regime-briefing-may-16-2026.html',
  'regime-briefing-dollar-2026':    '/articles/regime-briefing-dollar-may-2026.html',
  'essay-debt-cycle-2026':          '/articles/essay-debt-cycle-may-2026.html',
  'essay-1937-2026':                '/articles/essay-1937-jan-2026.html',
};

export const ARTICLE_TITLES = {
  'annual-letter-2025':             '2025: A Year of Positioning',
  'regime-briefing-may-2026':       'Late-Cycle Signals Accumulating',
  'regime-briefing-dollar-2026':    'Dollar Strength Index Approaching Extreme',
  'essay-debt-cycle-2026':          'The Long-Term Debt Cycle: Where Are We?',
  'essay-1937-2026':                'History Rhymes: 1937 and 2026',
};
